import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppins = localFont({
  src: "./fonts/Poppins/Poppins-Medium.ttf",
  variable: "--mypoppins",
});
const poppinsLight = localFont({
  src: "./fonts/Poppins/Poppins-Light.ttf",
  variable: "--poppins-light",
});
const poppinsThin = localFont({
  src: "./fonts/Poppins/Poppins-Thin.ttf",
  variable: "--poppins-thin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} ${poppinsLight} ${poppinsThin}`}
      >
        {children}
      </body>
    </html>
  );
}
